export const initialData = {
  information: {
    income: 0,
    outcome: 0,
  },
  jars: [
    {
      id: "1",
      name: "common",
      income: 0,
      outcome: 0,
      spendingDetail: [],
      percent: 55,
    },
    {
      id: "2",
      name: "study",
      income: 0,
      outcome: 0,
      spendingDetail: [],
      percent: 10,
    },
    {
      id: "3",
      name: "save",
      income: 0,
      outcome: 0,
      spendingDetail: [],
      percent: 10,
    },
    {
      id: "4",
      name: "investion",
      income: 0,
      outcome: 0,
      spendingDetail: [],
      percent: 10,
    },
    {
      id: "5",
      name: "enjoyment",
      income: 0,
      outcome: 0,
      spendingDetail: [],
      percent: 10,
    },
    {
      id: "6",
      name: "charity",
      income: 0,
      outcome: 0,
      spendingDetail: [],
      percent: 5,
    },
  ],
};

export const INIT_JARS_DATA = [
  {
    income: 0,
    outcome: 0,
    name: "Chi tiêu",
    spending: [],
    percent: 55,
  },
  {
    income: 0,
    outcome: 0,
    name: "Học tập",
    spending: [],
    percent: 10,
  },
  {
    income: 0,
    outcome: 0,
    name: "Tiết kiệm",
    spending: [],
    percent: 10,
  },
  {
    income: 0,
    outcome: 0,
    name: "Đầu tư",
    spending: [],
    percent: 10,
  },
  {
    income: 0,
    outcome: 0,
    name: "Hưởng thụ",
    spending: [],
    percent: 5,
  },
  {
    income: 0,
    outcome: 0,
    name: "Cho đi",
    spending: [],
    percent: 5,
  },
];
